### ISSUE TITLE
Introduce `only-replace-suffix-with` parameter

### ISSUE THREAD

**Issue by SebastianKuesters** [wemogy/get-release-version-action#40]
![IMG_1361](https://github.com/wemogy/get-release-version-action/assets/15349201/5654cead-bb9f-45b3-9333-5e92e561cedc)

```yaml
- name: Clone repository
  uses: actions/checkout@v4
  with:
    fetch-depth: 0

- uses: wemogy/get-release-version-action
  id: get-release-version
  with:
    prefix: "v"
    suffix: "beta"
    previous-version-suffix: "pre"
    bumping-suffix: "hotfix"
    only-bump-suffix: "true"
    create-tag: "true"

- run: echo ${{ steps.get-release-version.outputs.version }}
- run: echo ${{ steps.get-release-version.outputs.version-name }}
- run: echo ${{ steps.get-release-version.outputs.has-changes }}
```

## Inputs

| Input                  | Required | Default  | Description                                                             |
| ---------------------- | -------- | -------- | ----------------------------------------------------------------------- |
| `prefix`               | `false`  | `v`      | The prefix that should be prepended to the version.                     |
| `suffix`               | `false`  | `` | The suffix that should appended to the version.        |
| `previous-version-suffix` | `false` | `` | The suffix to use when searching for the previous version |
| `bumping-suffix`               | `false`  | `hotfix` | The suffix to append to the version, if `only-bump-suffix` is `true`        |
| `only-bump-suffix` | `false`  | `false`  | Set this, if you only want to bump the `bumping-suffix` instead of incrementing the version                       |
| `create-tag`           | `false`  | `true`   | Create a Git Tag for the version and push it if a remote is configured. |
